/**
 * This script ensures the OpenAPI schema file is accessible before build.
 *
 * The schema should be in: <project-root>/local-shared-data/openapi.json
 * Both local development and Vercel deployment need access to this file.
 *
 * In monorepo Vercel deployments, the entire repo is checked out, so
 * ../local-shared-data/openapi.json is accessible from the frontend directory.
 */

const fs = require("fs");
const path = require("path");
const { config } = require("dotenv");
const { createLogger } = require("./logger");

// Load environment variables
config({ path: ".env.local" });
config({ path: ".env" });

const logger = createLogger("check-openapi");

const openapiPath =
  process.env.OPENAPI_OUTPUT_FILE || "../local-shared-data/openapi.json";
const absolutePath = path.resolve(__dirname, "..", openapiPath);

logger.info(`Checking for OpenAPI schema at: ${absolutePath}`);

if (!fs.existsSync(absolutePath)) {
  logger.error("❌ ERROR: OpenAPI schema file not found!");
  logger.error(`Expected location: ${absolutePath}`);
  logger.error("");
  logger.error(
    "The OpenAPI schema should be generated by the backend before building the frontend.",
  );
  logger.error(
    "Run: cd backend && uv run python -m commands.generate_openapi_schema",
  );
  process.exit(1);
}

const stats = fs.statSync(absolutePath);
logger.info(`✅ OpenAPI schema found (${stats.size} bytes)`);
logger.info("");
